"""created table user and token

Revision ID: 8d358f244c08
Revises: 
Create Date: 2024-05-23 16:15:06.048985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d358f244c08"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashedPassword", sa.String(), nullable=True),
        sa.Column("userName", sa.String(), nullable=True),
        sa.Column("isAdmin", sa.Boolean(), nullable=True),
        sa.Column("rndstr", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("rndstr"),
        sa.UniqueConstraint("userName"),
    )
    op.create_table(
        "Token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("refreshToken", sa.String(), nullable=True),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Token_id"), "Token", ["id"], unique=False)
    op.create_index(
        op.f("ix_Token_refreshToken"), "Token", ["refreshToken"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Token_refreshToken"), table_name="Token")
    op.drop_index(op.f("ix_Token_id"), table_name="Token")
    op.drop_table("Token")
    op.drop_table("User")
    # ### end Alembic commands ###
